"""
WAF (Web Application Firewall) Detection

Safe mode:
  - Analyzes response headers and cookies for WAF fingerprints
  - Detects: Cloudflare, AWS CloudFront/WAF, Sucuri, ModSecurity, Imperva/Incapsula,
             Akamai, F5 BIG-IP ASM, Barracuda, Wordfence, Nginx WAF, Fortiweb

Aggressive mode (additional):
  - Sends a deliberately crafted probe payload to trigger WAF blocking
  - Compares normal response vs probe response
  - Identifies WAF provider from error page fingerprints

Finding codes:
  HEPH-WAF-001  WAF detected via response headers/cookies (info)
  HEPH-WAF-002  WAF confirmed by blocking behavior (info)

Note: WAF presence is informational and REDUCES the severity of other findings.
      The description will note this context.

Author: Rodney Dhavid Jimenez Chacin (rodhnin)
License: MIT
"""

import re
from typing import List, Dict, Any, Optional, Tuple

import requests

from ..core.logging import get_logger
from ..core.config import get_config

logger = get_logger(__name__)

# WAF probe payload: URL-encoded SQL injection + XSS that any WAF should block
# Safe enough not to cause actual damage but reliably triggers WAF rules
WAF_PROBE_PARAMS = "?id=1%27%20OR%20%271%27%3D%271&q=%3Cscript%3Ealert%28xss%29%3C%2Fscript%3E"

# WAF signature definitions
# Each entry: (provider_name, detection_rules)
# Rules are checked against headers, cookies, server header, and response body
WAF_SIGNATURES = [
    (
        'Cloudflare',
        {
            'headers': ['CF-Ray', 'CF-Cache-Status', 'CF-Edge-Cache', 'CF-Request-ID'],
            'server_pattern': re.compile(r'cloudflare', re.I),
            'cookie_patterns': [re.compile(r'^(__cfduid|__cf_bm|cf_clearance)', re.I)],
            'block_body': re.compile(r'cloudflare|ray id|please wait|attention required', re.I),
        }
    ),
    (
        'AWS CloudFront',
        {
            'headers': ['X-Amz-Cf-Id', 'X-Amz-Cf-Pop', 'X-Amz-Request-Id'],
            'via_pattern': re.compile(r'cloudfront', re.I),
            'x_cache_pattern': re.compile(r'cloudfront', re.I),
            'block_body': re.compile(r'request blocked|cloudfront|generated by cloudfront', re.I),
        }
    ),
    (
        'AWS WAF',
        {
            'headers': ['X-AMZ-WAF-Action', 'X-Amzn-Trace-Id'],
            'block_body': re.compile(r'aws waf|request has been blocked', re.I),
        }
    ),
    (
        'Sucuri',
        {
            'headers': ['X-Sucuri-ID', 'X-Sucuri-Cache', 'X-Sucuri-Block'],
            'cookie_patterns': [re.compile(r'^sucuri_cloudproxy_uuid_', re.I)],
            'block_body': re.compile(r'sucuri website firewall|access denied.*sucuri', re.I),
        }
    ),
    (
        'ModSecurity',
        {
            'headers': ['X-Protected-By', 'X-Powered-By-Plesk'],
            'server_pattern': re.compile(r'mod_security|modsecurity', re.I),
            'x_protected_pattern': re.compile(r'mod_security|modsecurity', re.I),
            'block_body': re.compile(r'mod_security|modsecurity|not acceptable.*web application firewall', re.I),
        }
    ),
    (
        'Imperva Incapsula',
        {
            'headers': ['X-Iinfo', 'X-CDN'],
            'cookie_patterns': [
                re.compile(r'^incap_ses_', re.I),
                re.compile(r'^visid_incap_', re.I),
            ],
            'block_body': re.compile(r'incapsula|imperva|request unsuccessful', re.I),
        }
    ),
    (
        'Akamai',
        {
            'headers': ['X-Akamai-Transformed', 'X-Check-Cacheable', 'X-Akamai-Request-ID',
                        'X-Akamai-SSL-Client-Sid', 'Akamai-Cache-Status'],
            'via_pattern': re.compile(r'akamai', re.I),
            'block_body': re.compile(r'akamai|reference #\d+\.\d+\.', re.I),
        }
    ),
    (
        'F5 BIG-IP ASM',
        {
            'headers': ['X-WA-Info', 'X-Cnection'],
            'server_pattern': re.compile(r'bigip|big-ip', re.I),
            'cookie_patterns': [re.compile(r'^TS[0-9a-f]{8}', re.I)],
            'block_body': re.compile(r'the requested url was rejected|f5 networks|big-ip', re.I),
        }
    ),
    (
        'Barracuda WAF',
        {
            'cookie_patterns': [re.compile(r'^barra_counter_session', re.I)],
            'block_body': re.compile(r'barracuda networks|barra_counter|you cannot access', re.I),
        }
    ),
    (
        'Wordfence',
        {
            'block_body': re.compile(r'wordfence|generated by wordfence', re.I),
        }
    ),
    (
        'Fortiweb',
        {
            'headers': ['X-Powered-By-Fortinet'],
            'cookie_patterns': [re.compile(r'^FORTIWAFSID=', re.I)],
            'block_body': re.compile(r'fortigate|fortiweb|your request has been blocked', re.I),
        }
    ),
    (
        'Nginx ModSecurity WAF',
        {
            'server_pattern': re.compile(r'nginx.*\(.*modsecurity|openresty', re.I),
            'block_body': re.compile(r'openresty|lua nginx', re.I),
        }
    ),
    (
        'Wallarm',
        {
            'headers': ['X-Wallarm-Node'],
            'block_body': re.compile(r'wallarm', re.I),
        }
    ),
]


class WAFDetector:
    """
    Web Application Firewall detection engine.

    Uses header analysis in safe mode and active probing in aggressive mode.
    WAF detection is informational — it helps contextualize other findings.
    """

    def __init__(self, config=None, http_client=None, mode: str = 'safe'):
        self.config = config or get_config()
        self.http_client = http_client
        self.mode = mode

    def scan(self, target: str) -> List[Dict[str, Any]]:
        """
        Detect WAF presence on the target.
        """
        findings = []

        # --- Safe: Fetch main page and analyze headers ---
        normal_response = None
        try:
            normal_response = self.http_client.get(
                target,
                timeout=(self.config.timeout_connect, self.config.timeout_read),
                allow_redirects=True
            )
        except requests.exceptions.RequestException as e:
            logger.debug(f"WAF detection main page request failed: {e}")
            return findings
        except Exception as e:
            logger.debug(f"WAF detection unexpected error: {e}")
            return findings

        detected_waf, detection_details = self._fingerprint_from_response(normal_response)

        if detected_waf:
            findings.append(self._make_waf_finding(
                'HEPH-WAF-001',
                detected_waf,
                detection_details,
                target,
                confirmed=False
            ))
            logger.info(f"WAF detected (header analysis): {detected_waf}")
            return findings  # Already found — no need to probe

        # --- Aggressive: Send probe payload ---
        if self.mode == 'aggressive':
            probe_url = target.rstrip('/') + '/' + WAF_PROBE_PARAMS
            probe_response = None

            try:
                probe_response = self.http_client.get(
                    probe_url,
                    timeout=(self.config.timeout_connect, self.config.timeout_read),
                    allow_redirects=False
                )
            except requests.exceptions.RequestException:
                pass
            except Exception as e:
                logger.debug(f"WAF probe request failed: {e}")

            if probe_response is not None:
                blocked = probe_response.status_code in (403, 406, 429, 503, 400)
                waf_name, details = self._fingerprint_from_response(probe_response)

                if blocked or waf_name:
                    provider = waf_name or 'Unknown WAF'
                    findings.append(self._make_waf_finding(
                        'HEPH-WAF-002',
                        provider,
                        details or f'Probe payload triggered HTTP {probe_response.status_code}',
                        target,
                        confirmed=True,
                        probe_status=probe_response.status_code
                    ))
                    logger.info(f"WAF confirmed by probe ({probe_response.status_code}): {provider}")

        return findings

    def _fingerprint_from_response(
        self, response: requests.Response
    ) -> Tuple[Optional[str], Optional[str]]:
        """
        Analyze a response for WAF fingerprints.
        Returns (waf_name, detection_details) or (None, None).
        """
        headers = response.headers
        body = response.text[:5000]  # Only need first 5KB for body checks
        cookies_str = '; '.join(
            f'{c.name}={c.value}' for c in response.cookies
        )

        for waf_name, rules in WAF_SIGNATURES:
            matched_details = []

            # Check response headers for WAF-specific header names
            if 'headers' in rules:
                for h in rules['headers']:
                    if h in headers:
                        matched_details.append(f'header: {h}: {headers[h][:80]}')

            # Check Server header
            server = headers.get('Server', '')
            if 'server_pattern' in rules and rules['server_pattern'].search(server):
                matched_details.append(f'Server: {server}')

            # Check Via header
            via = headers.get('Via', '')
            if 'via_pattern' in rules and rules['via_pattern'].search(via):
                matched_details.append(f'Via: {via}')

            # Check X-Cache header
            x_cache = headers.get('X-Cache', '') + headers.get('x-cache', '')
            if 'x_cache_pattern' in rules and rules['x_cache_pattern'].search(x_cache):
                matched_details.append(f'X-Cache: {x_cache}')

            # Check X-Protected-By
            x_prot = headers.get('X-Protected-By', '')
            if 'x_protected_pattern' in rules and rules['x_protected_pattern'].search(x_prot):
                matched_details.append(f'X-Protected-By: {x_prot}')

            # Check cookies
            if 'cookie_patterns' in rules:
                for pattern in rules['cookie_patterns']:
                    if pattern.search(cookies_str):
                        matched_details.append(f'cookie: {pattern.pattern}')

            # Check response body (only for block pages)
            if 'block_body' in rules and rules['block_body'].search(body):
                m = rules['block_body'].search(body)
                matched_details.append(f'body: "{m.group(0)[:60]}"')

            if matched_details:
                return waf_name, ' | '.join(matched_details)

        return None, None

    def _make_waf_finding(
        self,
        finding_id: str,
        waf_name: str,
        detection_details: Optional[str],
        target: str,
        confirmed: bool = False,
        probe_status: Optional[int] = None,
    ) -> Dict[str, Any]:
        method = 'active probe' if confirmed else 'passive header analysis'
        title_suffix = ' (confirmed by probe)' if confirmed else ''

        return {
            'id': finding_id,
            'title': f'{waf_name} WAF detected{title_suffix}',
            'severity': 'info',
            'confidence': 'high' if confirmed else 'medium',
            'description': (
                f'{waf_name} Web Application Firewall detected via {method}. '
                f'WAF presence reduces the practical exploitability of some findings '
                f'(e.g., XSS, SQLi) but does NOT eliminate them — WAFs are bypassable '
                f'and should not replace secure coding practices.'
                + (f' Probe payload returned HTTP {probe_status}.' if probe_status else '')
            ),
            'evidence': {
                'type': 'header',
                'value': target,
                'context': detection_details or f'{waf_name} signature matched'
            },
            'recommendation': (
                f'WAF ({waf_name}) is active — this is generally positive. '
                f'Ensure the WAF is kept up to date with current rule sets. '
                f'Do not rely solely on the WAF — fix underlying vulnerabilities in application code.'
            ),
            'references': [
                'https://owasp.org/www-project-web-security-testing-guide/latest/4-Web_Application_Security_Testing/01-Information_Gathering/09-Fingerprint_Web_Application_Firewall',
            ],
        }
